version: '3.8'

services:
  api_gateway:
    build:
      context: ./apps/api_gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - user_service
      - content_service
      - order_service
      - wallet_service
      - social_service
      - governance_service
      - reward_service
      - search_service
      - notification_service
      - analytics_service

  user_service:
    build:
      context: ./services/user_service
      dockerfile: Dockerfile
    ports:
      - "3001:3000"

  content_service:
    build:
      context: ./services/content_service
      dockerfile: Dockerfile
    ports:
      - "3002:3000"

  order_service:
    build:
      context: ./services/order_service
      dockerfile: Dockerfile
    ports:
      - "3003:3000"

  wallet_service:
    build:
      context: ./services/wallet_service
      dockerfile: Dockerfile
    ports:
      - "3004:3000"

  social_service:
    build:
      context: ./services/social_service
      dockerfile: Dockerfile
    ports:
      - "3005:3000"

  governance_service:
    build:
      context: ./services/governance_service
      dockerfile: Dockerfile
    ports:
      - "3006:3000"

  reward_service:
    build:
      context: ./services/reward_service
      dockerfile: Dockerfile
    ports:
      - "3007:3000"

  search_service:
    build:
      context: ./services/search_service
      dockerfile: Dockerfile
    ports:
      - "3008:3000"

  notification_service:
    build:
      context: ./services/notification_service
      dockerfile: Dockerfile
    ports:
      - "3009:3000"

  analytics_service:
    build:
      context: ./services/analytics_service
      dockerfile: Dockerfile
    ports:
      - "3010:3000"

networks:
  default:
    driver: bridge