rootAction:
  key: uptuel51
  action:
    key: 37nnttt1
  followUpAction:
    key: 4yi8bezl
    action:
      key: 60ykxkdo
    followUpAction:
      key: c55fl9m3
      action:
        key: v35oh79z
trigger:
  triggerType: ON_TAP