rootAction:
  key: gsyvltzl
  conditionActions:
    falseAction:
      key: b5s0bux6
      action:
        key: dtqrbc7x
    trueActions:
      - condition:
          variable:
            source: FUNCTION_CALL
            functionCall:
              values:
                - variable:
                    source: WIDGET_STATE
                    baseVariable:
                      widgetState:
                        returnParameter:
                          allowedDestinationTypes:
                            - Integer
                            - Double
                            - Boolean
                            - ImagePath
                            - VideoPath
                            - AudioPath
                          dataType:
                            scalarType: String
                    nodeKeyRef:
                      key: TextField_0mh66lvt
                - variable:
                    source: FIRESTORE_REQUEST
                    baseVariable:
                      firestore: {}
                    operations:
                      - accessDocumentField:
                          documentProperty: REFERENCE
                      - documentReferenceId: {}
                    nodeKeyRef:
                      key: Column_enujka9q
              condition:
                relation: EQUAL_TO
        trueAction:
          key: brajw5d4
          action:
            key: fmg3h9ol
          followUpAction:
            key: ueij5j4v
            action:
              key: 6y35oc7n
            followUpAction:
              key: kj0hxk82
              action:
                key: phhqi38s
    hasMultiConditions: false
    key: wnslphr9
trigger:
  triggerType: ON_TAP