templateType: LARGE_HEADER_BACK_BUTTON
backgroundColor:
  themeColor: PRIMARY
height:
  pixelsValue:
    inputValue: 40
    mostRecentInputValue: 40
defaultIcon:
  sizeValue:
    inputValue: 30
    mostRecentInputValue: 30
  colorValue:
    inputValue:
      value: "4294967295"
    mostRecentInputValue:
      value: "4294967295"
  iconDataValue:
    inputValue:
      codePoint: 62834
      family: MaterialIcons
      matchTextDirection: true
      name: arrow_back_rounded
textStyle:
  themeStyle: HEADLINE_MEDIUM
  fontSizeValue:
    inputValue: 22
    mostRecentInputValue: 22
  colorValue:
    inputValue:
      value: "4294967295"
    mostRecentInputValue:
      value: "4294967295"
addOnNewPages: false
responsiveVisibility:
  phoneHidden: false