rootAction:
  key: vxsv452t
  conditionActions:
    falseAction:
      key: e7ehitst
      action:
        key: 4x0s0wee
    trueActions:
      - condition:
          variable:
            source: FUNCTION_CALL
            functionCall:
              values:
                - variable:
                    source: FIRESTORE_REQUEST
                    baseVariable:
                      firestore: {}
                    operations:
                      - accessDocumentField:
                          fieldIdentifier:
                            name: poster
                    nodeKeyRef:
                      key: Container_jlipacve
                - variable:
                    source: FIREBASE_AUTH_USER
                    baseVariable:
                      auth:
                        property: USER_REFERENCE
              condition:
                relation: NOT_EQUAL_TO
        trueAction:
          key: 65trj5nq
          action:
            key: dy4g21dv
          followUpAction:
            key: 8xzweajm
            action:
              key: umbowgl4
    hasMultiConditions: false
trigger:
  triggerType: ON_TAP